/// <reference path="../../Scripts/config/scene.ts"/>
/// <reference path="../../Scripts/objects/game.ts"/>
/// <reference path="../../Scripts/objects/scene.ts"/>
/// <reference path="../../Scripts/objects/button.ts"/>
/// <reference path="../../Scripts/objects/label.ts"/>
/// <reference path="../../Scripts/objects/background.ts"/>
/// <reference path="../../Scripts/objects/gameobject.ts"/>
/// <reference path="../../Scripts/objects/plane.ts"/>
/// <reference path="../../Scripts/objects/missile.ts"/>
/// <reference path="../../Scripts/objects/enemy.ts"/>
/// <reference path="../../Scripts/objects/vector2.ts"/>
/// <reference path="../../Scripts/scenes/opening.ts"/>
/// <reference path="../../Scripts/scenes/choosemode.ts"/>
/// <reference path="../../Scripts/scenes/play.ts"/>
/// <reference path="../../Scripts/scenes/gameover.ts"/>
/// <reference path="../../Scripts/managers/collision.ts"/>
//# sourceMappingURL=_reference.js.map